import type { Metadata } from "next";
import { Inter as GoogleInter } from "next/font/google";

import { QueryProvider } from "@/components/query-provider";

import { cn } from "@/lib/utils";

import "./globals.css";

const inter = GoogleInter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        <QueryProvider>
          {children}
        </QueryProvider>
        
      </body>
    </html>
  );
}
